; Measure 1
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_3, YM_KC_G, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_B, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_4
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT3
WAIT_HALF_BEAT
; Measure 2
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_B, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT6
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT6
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT4
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
WAIT_HALF_BEAT
WAIT_HALF_BEAT
; Measure 3
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_A, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_A, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_A, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_A, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
; Measure 4
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_A, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_A, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_F_SH, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_F_SH, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_F_SH, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_F_SH, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_A, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_A, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
WAIT_HALF_BEAT
WAIT_HALF_BEAT
; Measure 5
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
REST YM_CH_1
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
REST YM_CH_5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
; Measure 6
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_C, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_F_SH, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
; Measure 7
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
; Measure 8
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
REST YM_CH_8
WAIT_HALF_BEAT
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_C, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_C, YM_KC_OCT3
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_C, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_F_SH, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
; Measure 9
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_3, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_B, YM_KC_OCT3
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT4
REST YM_CH_3
NOTE YM_CH_4, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_F_SH, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_E, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_E, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_4, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_B, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_D, YM_KC_OCT5
NOTE YM_CH_4, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_D, YM_KC_OCT5
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_F_SH, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_A, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_C, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_F_SH, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_B, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_F_SH, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_G, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_B, YM_KC_OCT4
WAIT_HALF_BEAT
; Measure 10
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_G, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_G, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_F_SH, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_C, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_F_SH, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_A, YM_KC_OCT3
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_2, YM_KC_F_SH, YM_KC_OCT4
NOTE YM_CH_4, YM_KC_A, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_B, YM_KC_OCT5
NOTE YM_CH_6, YM_KC_F_SH, YM_KC_OCT4
WAIT_HALF_BEAT
NOTE YM_CH_1, YM_KC_D, YM_KC_OCT6
NOTE YM_CH_2, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_3, YM_KC_D, YM_KC_OCT3
NOTE YM_CH_4, YM_KC_B, YM_KC_OCT2
NOTE YM_CH_5, YM_KC_D, YM_KC_OCT6
NOTE YM_CH_6, YM_KC_G, YM_KC_OCT4
NOTE YM_CH_7, YM_KC_D, YM_KC_OCT4
NOTE YM_CH_8, YM_KC_B, YM_KC_OCT3
WAIT_HALF_BEAT
WAIT_HALF_BEAT
REST YM_CH_1
REST YM_CH_2
REST YM_CH_3
REST YM_CH_4
REST YM_CH_5
REST YM_CH_6
REST YM_CH_7
REST YM_CH_8
WAIT_HALF_BEAT
WAIT_HALF_BEAT
; Measure 11+?
END_MUSIC
